// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import AosController from "./aos_controller"
application.register("aos", AosController)

import BookingFormPriceController from "./booking_form_price_controller"
application.register("booking-form-price", BookingFormPriceController)

import Carousel from 'stimulus-carousel'
application.register('carousel', Carousel)

import CategorySelectorController from "./category_selector_controller"
application.register("category-selector", CategorySelectorController)

import DropdownMenuController from "./dropdown_menu_controller"
application.register("dropdown-menu", DropdownMenuController)

import HideDeviseAlertController from "./hide_devise_alert_controller"
application.register("hide-devise-alert", HideDeviseAlertController)

import MapController from "./map_controller"
application.register("map", MapController)

import PhotoUploaderController from "./photo_uploader_controller"
application.register("photo-uploader", PhotoUploaderController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TypedController from "./typed_controller"
application.register("typed", TypedController)
